### ISSUE TITLE
Cannot deserialize session for anonymous users

### ISSUE THREAD

**Issue by anthony-foulfoin** [AusDTO/spring-security-stateless#2]
Hi,

I have an issue regarding the anonymous users when using this library. When the user is not logged in yet,  I get the following exception : 

`
java.lang.RuntimeException: Problem deserializing JSON to Authentication
	at au.gov.dto.springframework.security.web.context.JsonAuthenticationSerializer.deserialize(JsonAuthenticationSerializer.java:49) ~[spring-security-stateless-v1.2.3.jar:null]
	at au.gov.dto.springframework.security.web.context.CookieSecurityContextRepository.loadContext(CookieSecurityContextRepository.java:65) ~[spring-security-stateless-v1.2.3.jar:null]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:86) ~[spring-security-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.springframework.security.authentication.AnonymousAuthenticationToken]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"@class":"org.springframework.security.authentication.AnonymousAuthenticationToken","details":{"@class":"org.springframework.security.web.authentication.WebAuthenticationDetails","remoteAddress":"0:0:0:0:0:0:0:1","sessionId":null},"authorities":["java.util.ArrayList",[{"@class":"org.springframework.security.core.authority.SimpleGrantedAuthority","role":"ROLE_ANONYMOUS"}]],"authenticated":true,"principal":"anonymousUser","keyHash":-2102752285,"credentials":"","name":"anonymousUser"}; line: 1, column: 85]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.7.jar:2.6.7]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106) ~[jackson-databind-2.6.7.jar:2.6.7]
`

Seems like the AnonymousAuthenticationToken is not properly handled.
If I add **.anonymous().disable()**, I get another exception : 

`
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:378)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:222)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
`

**Comment by halvards** [comment]
You're right that AnonymousAuthenticationToken isn't handled by this library. 

You'll need to ensure that the paths/endpoints of your application that don't require authentication are ignored by Spring Security. The included sampleapp does this on [line 63 of WebSecurityConfig.java](https://github.com/AusDTO/spring-security-stateless/blob/master/src/sampleapp/java/au/gov/dto/springframework/security/sample/config/WebSecurityConfig.java#L63)

The challenge with AnonymousAuthenticationToken is that it contains a field called 'keyHash' that is verified on return visits by anonymous users. For this reason the 'key' used to calculate 'keyHash' on instantiation would also have to be synchronised across all servers involved.

**Comment by gustavofossati** [comment]
Hi halvards,
Very good code! 
Please excuse my poor english.
We are experimenting with your library as a posible cookie based solution in a load balancing architecture without sticky session (more scalable than spring session jdbc). Project is based on Oauth2 and security spring library.
We are working with a AnonymousAuthenticationTokenDeserializer and reflection (setKeyHash) to solve AnonymousAuthenticationToken constructor issue, this is ok for you?
I not understand AnonymousAuthenticationToken challenge, is this solvable?
Thanks very much
Gustavo
