### ISSUE TITLE
An attempt was made to write more data to the response headers than there was room available in the buffer

### ISSUE THREAD

**Issue by abedurftig** [AusDTO/spring-security-stateless#3]
Hello, thanks for your library.

Following your example, I get the following exception. I believe it is the `authentication` cookie.

`org.apache.coyote.http11.HeadersTooLargeException: An attempt was made to write more data to the response headers than there was room available in the buffer. Increase maxHttpHeaderSize on the connector or write less data into the response headers.
	at org.apache.coyote.http11.Http11OutputBuffer.checkLengthBeforeWrite(Http11OutputBuffer.java:458) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:411) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:397) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:357) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:974) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:351) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.Response.action(Response.java:211) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.Response.sendHeaders(Response.java:437) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:280) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:240) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.connector.Response.finishResponse(Response.java:441) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:374) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.12.jar:9.0.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.12.jar:9.0.12]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]`

**Comment by abedurftig** [comment]
This can be solved with the following property.

`server.max-http-header-size=128KB`
